app_config: {}
data_config: {datapath: ../../images}
gui_config:
  fruit_config:
    apple: [a, b, c, d]
    lemon: ["\u7EA7\u522B", "\u91CD\u91CF", "\u4F53\u79EF"]
    passion: ["\u4F53\u79EF", "\u91CD\u91CF"]
  fruit_list: [lemon, apple, passion]
  height: 640
  width: 960
img_config:
  fruit: lemon
  height: 175
  points:
  - !!python/tuple [0,50]
  - !!python/tuple [185, 50]
  - !!python/tuple [370, 50]
  - !!python/tuple [550, 50]
  - !!python/tuple [720, 50]
  - !!python/tuple [900, 50]
  width: 150
